---
version: 1
default_ip_start_address: "192.168.68.2"
#default_network_name:
servers:
  - server1:
    #ssh_username:
    #ssh_password:
    #ssh_private_key_path:
    #ssh_forward_agent:
    #ssh_insert_key:
    libvirt:
      hostname: "server1"
      box: "fedora/24-cloud-base"
