---
version: 1
default_ip_start_address: "192.168.68.2"
#default_network_name:
servers:
  - server1:
    synced_folders:
    - source: "./"
      dest: "/vagrant"
      type: "rsync"
      disabled: "true"
    libvirt:
      #hostname, box, box_url are to be overriden with provider specific info
      hostname: "server1"
      box: "fedora/24-cloud-base"
      #box_url:
      #domain options
      memory: 1024
      cpus: 1
      nested: true
      #network definitions
      networks:
      - identifier: "private_network" #or public_network, see below
        auto_config: true
        ip:  192.168.134.33 #OR type: dhcp
        libvirt__network_name: "vcc_vagrant_new"
        libvirt__netmask: 255.255.255.0
        libvirt__dhcp_enabled: true
        libvirt__dhcp_start: 192.168.134.128
        libvirt__dhcp_stop: 192.168.134.254
        libvirt__forward_mode: "nat" #OR nat, route, veryisolated
      - identifier: "public_network" #Use this only if you know what it does
        dev: "enp0s25"
      disks:
      - count: 1
        size: "1G"
      - count: 5
